replicaCount: 1

image:
  repository: coturn/coturn
  tag: 4.6.2
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  ports:
    - name: turn-udp
      port: 3478
      protocol: UDP
      targetPort: 3478
    - name: turn-tcp
      port: 3478
      protocol: TCP
      targetPort: 3478
    - name: turn-tls
      port: 5349
      protocol: TCP
      targetPort: 5349
  annotations: {}

podAnnotations: {}

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  readOnlyRootFilesystem: true
  capabilities:
    add: ["NET_BIND_SERVICE"]
    drop: ["ALL"]
  seccompProfile:
    type: RuntimeDefault

config:
  turnserver.conf: |
    listening-port=3478
    tls-listening-port=5349
    min-port=49152
    max-port=65535
    verbose
    #fingerprint
    #lt-cred-mech
    #use-auth-secret
    #static-auth-secret=my-secret
    #realm=my-realm.example.com
    #user=healthcheck:healthcheckpassword
    #cli-password=adminpassword
    no-auth
    no-stun

probes:
  liveness:
    enabled: false
    initialDelaySeconds: 45  # Increased delay for TURN server initialization
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  readiness:
    enabled: false
    initialDelaySeconds: 20
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
