apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coturn.fullname" . }}-config
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
data:
  {{- .Values.config | toYaml | nindent 2 }}
